version: 0.0
os: linux

files:
  - source: imageDetail.txt
    destination: /opt/scripts/
  - source: deploy.sh
    destination: /opt/scripts/

permissions:
  - object: /opt/scripts/deploy.sh
    pattern: "**"
    owner: root
    mode: "0755"

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: root
