version: 0.2
phases:
  pre_build:
    commands:
      - echo "Fetching Docker Hub credentials from AWS Secrets Manager..."
      - export DOCKERHUB_USERNAME=$(aws secretsmanager get-secret-value --secret-id dockerhub-credentials --query 'SecretString' --output text | jq -r .DOCKERHUB_USERNAME)
      - export DOCKERHUB_PASSWORD=$(aws secretsmanager get-secret-value --secret-id dockerhub-credentials --query 'SecretString' --output text | jq -r .DOCKERHUB_PASSWORD)
      - echo "Logging into Docker Hub..."
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - export IMAGE_NAME="biswojit01/secure:django-V1"
      - echo "Image name: $IMAGE_NAME"
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t "$IMAGE_NAME" .
  post_build:
    commands:
      - echo "Pushing Docker image to private Docker Hub repository..."
      - docker push "$IMAGE_NAME"
      - echo "IMAGE=$IMAGE_NAME" > imageDetail.txt
      - cat imageDetail.txt
artifacts:
  files:
    - imageDetail.txt
